services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: docdb
      MYSQL_USER: docuser
      MYSQL_PASSWORD: docpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: doc-ocr-api
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
       DB_HOST: mysql

volumes:
  mysql_data:
